### ISSUE TITLE
Why wouldn't we have APIService provided/injected as a dependency as well?

### ISSUE THREAD

**Issue by sleepylee** [luongvo/SurveysApp#5]
![image](https://user-images.githubusercontent.com/13435717/45132977-2e636000-b1bd-11e8-88ab-c1f7d9dabbd6.png)

**Comment by luongvo** [comment]
@sleepylee lack of comment, it made for context initializing for APIService instance to query access token when adding into headers

**Comment by oakkub** [comment]
I think we can move AppConfigureHelper and APIService to be in a dagger module and the application's context can also be in dagger module as well so that we could initialize AppConfigureHelper and then inject them to APIService. What do you think 🤔

**Comment by luongvo** [comment]
@oakkub @sleepylee Move them into dagger module could be a nice idea to refactor this case. Gson builder also could be moved into dagger too. I will come back to handle them at the end of this day.
