### ISSUE TITLE
Access directly to AppConfigureHelper isn't a nice idea.

### ISSUE THREAD

**Issue by sleepylee** [luongvo/SurveysApp#7]
It's violating the SOLI**D** principle to have its instance access from the different layer directly, this could cause the unit not isolated or, retrievable via an interface, and hence, hard to test. How do you think?

**Comment by luongvo** [comment]
@sleepylee It should be same to #5 when doing refactoring 🚀

**Comment by sleepylee** [comment]
this issue has not been resolved.

**Comment by luongvo** [comment]
@sleepylee how about this? #11

**Comment by sleepylee** [comment]
@luongvo good try, but it's still not reaching our goal from the comment of this ticket. 1 of the key thing we can benefit from not associating with the real SharePreferences is that retrieving the data can be mocked easier to serve the unit testing purpose, as well as the extendability/replacement later if we communicate over interfaces. 

I think this is ok for now with your tries, let's moving on another issue to save your time.
